apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Values.client.name }}
  namespace: io-cluster-tsdb
spec:
  cluster:
    name: timescaledb-cluster

  name: {{ .Values.client.name }}
  owner: {{ .Values.client.name }}

  ensure: present
  databaseReclaimPolicy: delete

  extensions:
    - name: timescaledb
      schema: public