import { getPoolStats } from '../db/connection';
import { metrics } from './metrics';

export function renderIngestionPrometheusMetrics(): string {
  const lines: string[] = [];
  const dbPool = getPoolStats();

  lines.push('# HELP iotistic_ingestion_stream_length Current number of messages in the ingestion stream backlog');
  lines.push('# TYPE iotistic_ingestion_stream_length gauge');
  lines.push(`iotistic_ingestion_stream_length ${metrics.streamLength}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_worker_lag Undelivered messages in the consumer group (stream lag)');
  lines.push('# TYPE iotistic_ingestion_worker_lag gauge');
  lines.push(`iotistic_ingestion_worker_lag ${metrics.workerLag}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_pending_count Delivered but unacknowledged messages (PEL size)');
  lines.push('# TYPE iotistic_ingestion_pending_count gauge');
  lines.push(`iotistic_ingestion_pending_count ${metrics.pendingMessages}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_dlq_length Number of messages in the dead-letter queue');
  lines.push('# TYPE iotistic_ingestion_dlq_length gauge');
  lines.push(`iotistic_ingestion_dlq_length ${metrics.dlqLength}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_worker_count Number of active ingestion worker loops');
  lines.push('# TYPE iotistic_ingestion_worker_count gauge');
  lines.push(`iotistic_ingestion_worker_count ${metrics.workerCount}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_process_cpu_percent Process CPU usage over the last sampler window as percent of one core');
  lines.push('# TYPE iotistic_ingestion_process_cpu_percent gauge');
  lines.push(`iotistic_ingestion_process_cpu_percent ${metrics.processCpuPercent}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_process_heap_used_bytes V8 heap used by the ingestion process');
  lines.push('# TYPE iotistic_ingestion_process_heap_used_bytes gauge');
  lines.push(`iotistic_ingestion_process_heap_used_bytes ${metrics.processHeapUsedBytes}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_process_heap_total_bytes Total V8 heap allocated to the ingestion process');
  lines.push('# TYPE iotistic_ingestion_process_heap_total_bytes gauge');
  lines.push(`iotistic_ingestion_process_heap_total_bytes ${metrics.processHeapTotalBytes}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_process_rss_bytes Resident set size of the ingestion process');
  lines.push('# TYPE iotistic_ingestion_process_rss_bytes gauge');
  lines.push(`iotistic_ingestion_process_rss_bytes ${metrics.processRssBytes}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_event_loop_delay_mean_ms Mean event loop delay over the last sampler window');
  lines.push('# TYPE iotistic_ingestion_event_loop_delay_mean_ms gauge');
  lines.push(`iotistic_ingestion_event_loop_delay_mean_ms ${metrics.eventLoopDelayMeanMs}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_event_loop_delay_p95_ms P95 event loop delay over the last sampler window');
  lines.push('# TYPE iotistic_ingestion_event_loop_delay_p95_ms gauge');
  lines.push(`iotistic_ingestion_event_loop_delay_p95_ms ${metrics.eventLoopDelayP95Ms}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_redis_connected Redis connectivity status (1=connected, 0=disconnected)');
  lines.push('# TYPE iotistic_ingestion_redis_connected gauge');
  lines.push(`iotistic_ingestion_redis_connected ${metrics.redisConnected}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_redis_memory_used_bytes Redis memory currently in use (bytes)');
  lines.push('# TYPE iotistic_ingestion_redis_memory_used_bytes gauge');
  lines.push(`iotistic_ingestion_redis_memory_used_bytes ${metrics.redisMemoryUsedBytes}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_redis_memory_max_bytes Redis maxmemory configuration in bytes (0=unlimited)');
  lines.push('# TYPE iotistic_ingestion_redis_memory_max_bytes gauge');
  lines.push(`iotistic_ingestion_redis_memory_max_bytes ${metrics.redisMemoryMaxBytes}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_batch_latency_p95_ms P95 producer enqueue duration into the Redis ingestion pipeline (ms)');
  lines.push('# TYPE iotistic_ingestion_batch_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_batch_latency_p95_ms ${metrics.getBatchLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_total_connections Total PostgreSQL pool connections currently tracked by the ingestion process');
  lines.push('# TYPE iotistic_ingestion_db_pool_total_connections gauge');
  lines.push(`iotistic_ingestion_db_pool_total_connections ${dbPool.total}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_idle_connections Idle PostgreSQL pool connections currently available');
  lines.push('# TYPE iotistic_ingestion_db_pool_idle_connections gauge');
  lines.push(`iotistic_ingestion_db_pool_idle_connections ${dbPool.idle}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_active_connections Active PostgreSQL pool connections currently in use');
  lines.push('# TYPE iotistic_ingestion_db_pool_active_connections gauge');
  lines.push(`iotistic_ingestion_db_pool_active_connections ${dbPool.active}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_waiting_requests PostgreSQL client requests currently waiting on a pool connection');
  lines.push('# TYPE iotistic_ingestion_db_pool_waiting_requests gauge');
  lines.push(`iotistic_ingestion_db_pool_waiting_requests ${dbPool.waiting}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_saturation_pct PostgreSQL pool active connection utilization as a percentage of configured max');
  lines.push('# TYPE iotistic_ingestion_db_pool_saturation_pct gauge');
  lines.push(`iotistic_ingestion_db_pool_saturation_pct ${dbPool.saturationPct}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_pool_configured_max Configured maximum PostgreSQL pool size for the ingestion process');
  lines.push('# TYPE iotistic_ingestion_db_pool_configured_max gauge');
  lines.push(`iotistic_ingestion_db_pool_configured_max ${dbPool.configuredMax}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_insert_latency_p95_ms P95 TimescaleDB batch insert duration (ms)');
  lines.push('# TYPE iotistic_ingestion_insert_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_insert_latency_p95_ms ${metrics.getInsertLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_resolve_latency_p95_ms P95 payload normalization and expansion duration (ms)');
  lines.push('# TYPE iotistic_ingestion_resolve_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_resolve_latency_p95_ms ${metrics.getResolveLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_ack_latency_p95_ms P95 Redis ACK pipeline duration (ms)');
  lines.push('# TYPE iotistic_ingestion_ack_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_ack_latency_p95_ms ${metrics.getAckLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_telemetry_latency_p95_ms P95 endpoint telemetry timestamp update duration (ms)');
  lines.push('# TYPE iotistic_ingestion_telemetry_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_telemetry_latency_p95_ms ${metrics.getTelemetryLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_processing_latency_p95_ms P95 end-to-end batch processing duration from read to ACK (ms)');
  lines.push('# TYPE iotistic_ingestion_processing_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_processing_latency_p95_ms ${metrics.getProcessingLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_dwell_latency_p95_ms P95 message dwell time in Redis stream before processing (ms)');
  lines.push('# TYPE iotistic_ingestion_dwell_latency_p95_ms gauge');
  lines.push(`iotistic_ingestion_dwell_latency_p95_ms ${metrics.getDwellLatencyP95()}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_messages_processed_total Total messages successfully committed to database');
  lines.push('# TYPE iotistic_ingestion_messages_processed_total counter');
  lines.push(`iotistic_ingestion_messages_processed_total ${metrics.messagesProcessed}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_readings_inserted_total Total sensor reading rows inserted into TimescaleDB');
  lines.push('# TYPE iotistic_ingestion_readings_inserted_total counter');
  lines.push(`iotistic_ingestion_readings_inserted_total ${metrics.readingsInserted}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_messages_failed_total Total messages that failed normalization');
  lines.push('# TYPE iotistic_ingestion_messages_failed_total counter');
  lines.push(`iotistic_ingestion_messages_failed_total ${metrics.messagesFailed}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_messages_dropped_total Total messages dropped due to OOM pressure');
  lines.push('# TYPE iotistic_ingestion_messages_dropped_total counter');
  lines.push(`iotistic_ingestion_messages_dropped_total ${metrics.messagesDropped}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_oom_errors_total Total OOM errors on Redis pipeline flush');
  lines.push('# TYPE iotistic_ingestion_oom_errors_total counter');
  lines.push(`iotistic_ingestion_oom_errors_total ${metrics.oomErrors}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_db_backpressure_events_total Total worker sleep events caused by DB pressure gating');
  lines.push('# TYPE iotistic_ingestion_db_backpressure_events_total counter');
  lines.push(`iotistic_ingestion_db_backpressure_events_total ${metrics.dbBackpressureEvents}`);
  lines.push('');
  lines.push('# HELP iotistic_ingestion_redis_reconnects_total Total Redis reconnection events');
  lines.push('# TYPE iotistic_ingestion_redis_reconnects_total counter');
  lines.push(`iotistic_ingestion_redis_reconnects_total ${metrics.redisReconnects}`);

  return `${lines.join('\n')}\n`;
}