{{- if and .Values.api .Values.api.enabled .Values.api.monitoring .Values.api.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iotistic.fullname" . }}-api
  labels:
    {{- include "iotistic.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.api.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "iotistic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: api
      path: /metrics
      interval: {{ .Values.api.monitoring.interval }}
      scrapeTimeout: {{ .Values.api.monitoring.scrapeTimeout }}
      {{- with .Values.api.monitoring.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
