{{- if .Values.api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iotistic-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iotistic.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
