---
# Virtual Agents Namespace for TSDB Customer
apiVersion: v1
kind: Namespace
metadata:
  name: virtual-agents-tsdb01
  labels:
    customer: tsdb
    iotistica.com/namespace-type: virtual-agents
    iotistica.com/billing-enabled: "true"
    iotistica.com/customer-id: tsdb01
