apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-rbac
spec:
  project: default
  source:
    repoURL: 'https://github.com/Iotistica/iot-k8s.git' # Replace with your Git repository URL
    targetRevision: main # Replace with the desired branch or tag
    path: cluster-rbac # Path to the directory containing cluster-roles.yaml
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false