apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provisioning
spec:
  project: default

  source:
    repoURL: https://github.com/Iotistica/iot-k8s.git
    targetRevision: main
    path: charts/provisioning
    helm:
      # explicit releaseName avoids empty-name bug seen previously
      releaseName: provisioning
      valueFiles:
        - values.yaml   # relative to charts/provisioning

  destination:
    server: https://kubernetes.default.svc
    namespace: provisioning

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true