apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app.fullname" . | trunc 63 | trimSuffix "-" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "simple-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}