apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-23963d1ee84e
spec:
  destination:
    namespace: client-23963d1ee84e
    server: https://kubernetes.default.svc
  source:
    path: charts/iotistica-app
    repoURL: https://github.com/Iotistica/iot-k8s.git
    targetRevision: main
    helm:
      valueFiles:
        - values/client-23963d1ee84e/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
