apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  project: default

  source:
    repoURL: https://github.com/Iotistica/iot-k8s.git
    targetRevision: main
    path: charts/iotistica-app
    helm:
      valueFiles:
        - values/demo/values.yaml   # relative to charts/iotistica-app

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true