name: Deploy Website

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: [arc-runner-set-iotistica-light-v2]
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy to Azure Static Web Apps
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_BAY_03A508210 }}
        run: swa deploy ./website --deployment-token "$SWA_CLI_DEPLOYMENT_TOKEN" --env production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: [arc-runner-set-iotistica-light-v2]
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_BAY_03A508210 }}
        run: |
          npm install -g @azure/static-web-apps-cli
          swa deploy --deployment-token "$SWA_CLI_DEPLOYMENT_TOKEN" --env close
