apiVersion: v1
kind: Secret
metadata:
  name: install-redirect-secrets
  namespace: iotistic-utils
type: Opaque
stringData:
  # Replace with your actual Azure Storage Account name
  AZURE_STORAGE_ACCOUNT: "your-storage-account"
